# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'git@github.com:quanshengzuIOSModulizationDemo/PodSpec.git'
source 'https://github.com/CocoaPods/Specs.git'

target '__ProjectName__' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'MJRefresh', '3.1.12'
pod 'Masonry', '1.0.2'
pod 'AFNetworking', '3.1.0'
pod 'YYModel'
pod 'YYWebImage'

end
